### ISSUE TITLE
Possible integration with ESPHome remote_transmitter.transmit_raw

### ISSUE THREAD

**Issue by TimelessNL** [Jev1337/NiceFlor-Encoder#1]
Hi @Jev1337.

Great work on the NiceFlor protocol!
I'm looking through your code and are trying to understand how to use this in my own project.
My plan is to use the [remote_transmitter component](https://esphome.io/components/remote_transmitter.html) from ESPHome controlled using its API or MQTT. This makes the transmitter really simple and as a bonus integrates nicely with HomeAssistant.

One thing I'm struggling with is the `send()` command and its output, I suspect the hexadecimal output needs to be converted to binary with the correct timings to accommodate for ~~manchester~~ tribit encoding. These raw timings should then be possible to be used with [remote_transmitter.transmit_raw Action](https://esphome.io/components/remote_transmitter.html#remote-transmitter-transmit-raw-action).

Can you give my any tips on using the output of `send()` and convert it over to raw timings?
Thanks in advance!

**Comment by TimelessNL** [comment]
I was able to port your python code to ESPHome using the following code:
```
#include <stdint.h>
#include <stdio.h>

uint64_t nice_flor_s_encode(uint32_t serial, uint32_t code, uint8_t button_id, uint8_t repeat)
{
    uint8_t snbuff[4] = {0};
    snbuff[0] = serial & 0xff;
    snbuff[1] = (serial & 0xff00) >> 8;
    snbuff[2] = (serial & 0xff0000) >> 16;
    snbuff[3] = (serial & 0xff000000) >> 24;

    uint64_t encbuff[7] = {0};
    uint16_t enccode    = pgm_read_word_near(nice_flor_s_table_decode + code);
    uint8_t ki          = nice_flor_s_table_ki[code & 0xff] ^ (enccode & 0xff);

    encbuff[0] = button_id & 0x0f;
    encbuff[1] = ((repeat ^ button_id ^ 0x0f) << 4) | ((snbuff[3] ^ ki) & 0x0f);
    encbuff[2] = enccode >> 8;
    encbuff[3] = enccode & 0xff;
    encbuff[4] = snbuff[2] ^ ki;
    encbuff[5] = snbuff[1] ^ ki;
    encbuff[6] = snbuff[0] ^ ki;

    uint64_t encoded = 0;
    encoded |= ((encbuff[6] << 0x4) & 0xF0) << 0;
    encoded |= (((encbuff[5] & 0x0F) << 4) | ((encbuff[6] & 0xF0) >> 4)) << 8;
    encoded |= (((encbuff[4] & 0x0F) << 4) | ((encbuff[5] & 0xF0) >> 4)) << 16;
    encoded |= (((encbuff[3] & 0x0F) << 4) | ((encbuff[4] & 0xF0) >> 4)) << 24;
    encoded |= (((encbuff[2] & 0x0F) << 4) | ((encbuff[3] & 0xF0) >> 4)) << 32;
    encoded |= (((encbuff[1] & 0x0F) << 4) | ((encbuff[2] & 0xF0) >> 4)) << 40;
    encoded |= (((encbuff[0] & 0x0F) << 4) | ((encbuff[1] & 0xF0) >> 4)) << 48;
    encoded = encoded ^ 0xFFFFFFFFFFFFF0;
    encoded = encoded >> 4;

    return encoded;
}

void nice_flor_s_tx_10(std::vector<int>* tx_buffer)
{
    tx_buffer->push_back(500);
    tx_buffer->push_back(-1000);
}

void nice_flor_s_tx_11(std::vector<int>* tx_buffer)
{
    tx_buffer->push_back(1000);
    tx_buffer->push_back(-500);
}

void nice_flor_s_tx_sync(std::vector<int>* tx_buffer)
{
    tx_buffer->push_back(1500);
    tx_buffer->push_back(-1500);
}

void nice_flor_s_tx_gap(std::vector<int>* tx_buffer)
{
    tx_buffer->push_back(15000);
}

std::vector<int> nice_flor_s_tx_generate(uint64_t data)
{
    std::vector<int> tx_buffer;

    nice_flor_s_tx_sync(&tx_buffer);

    unsigned char byte;
    int i, j = 0;
    unsigned char *b = (unsigned char*) &data;
    for (i = sizeof(data)-1; i >= 0; i--) {
        for (j = 7; j >= 0; j--) {
            byte = (b[i] >> j) & 1;
            if(byte){
               nice_flor_s_tx_10(&tx_buffer);
            }else{
               nice_flor_s_tx_11(&tx_buffer);
            }
        }
    }
   nice_flor_s_tx_gap(&tx_buffer);
   return tx_buffer;
}
```
With the following ESPHome config
```
esphome:
  name: niceflors
  friendly_name: niceflors

  includes:
    - ./niceflors/codes.h
    - ./niceflors/nice.h

remote_transmitter:
  pin: GPIO5
  id: transmitter
  carrier_duty_percent: 100%

number:
  - platform: template
    name: "Current Code"
    id: current_code
    optimistic: true
    min_value: 0
    max_value: 65535
    step: 1

  - platform: template
    name: "Repeat"
    id: repeat
    optimistic: true
    min_value: 1
    max_value: 7
    step: 1

  - platform: template
    name: "Button"
    id: button_id
    optimistic: true
    min_value: 1
    max_value: 2
    step: 1

button:
  - platform: template
    name: "Send signal"
    on_press:
      - remote_transmitter.transmit_raw:
          code: !lambda |-
            uint64_t encoded = nice_flor_s_encode(0x00E48DCA, id(current_code).state, id(button_id).state, id(repeat).state);
            return nice_flor_s_tx_generate(encoded);
```

It is still a work in progress, especially with the button, code, and repeat as input numbers. Using this method I can test my outcome against your examples. And so far they seem to match.

I'm still uncertain if the `nice_flor_s_tx_generate()` implementation is correct though as I'm currently unable to test the resulting signal.

I thought you might be interested, as this eliminates the need for a separate code generating API server as the entire thing can run on the ESP itself.
